### ISSUE TITLE
Unwanted symbols appear on generated images

### ISSUE THREAD

**Issue by DLumi** [clovaai/synthtiger#72]
I have my corpus set up like so. By design it contains only single characters (but I specified that in the config anyway).

```yaml
corpus:
  weights: [1]
  args:
    # length augmentable corpus
    - paths: [resources/corpus/mrz.txt]
      weights: [1]
      min_length: 1
      max_length: 1
      textcase: [upper]
      augmentation: 0
      augmentation_length: [0]
```

As for `char augmentable corpus`, I tried fiddling with the settings as well, but it does not seem to help.

So what happens is sometimes I get longer strings like so:
```
images/0/0.jpg	Z
images/0/1.jpg	O
images/0/4.jpg	4
images/0/3.jpg	4
images/0/5.jpg	N
images/0/8.jpg	A
images/0/6.jpg	P
images/0/10.jpg	9
images/0/2.jpg	HJ4I
images/0/7.jpg	K
images/0/11.jpg	I
images/0/9.jpg	E
images/0/13.jpg	S
images/0/15.jpg	M
images/0/14.jpg	V
images/0/16.jpg	Q
images/0/19.jpg	N
images/0/18.jpg	X
images/0/21.jpg	W
images/0/20.jpg	2
images/0/17.jpg	A
images/0/23.jpg	Q
images/0/22.jpg	M
images/0/25.jpg	K
images/0/27.jpg	U
images/0/24.jpg	X
images/0/26.jpg	YXN2MQ<7NP51CNUYTFI
```
![image](https://github.com/user-attachments/assets/42fbcc63-a04a-44da-85a1-2d8ca5689362)

And this is despite the fact that this simply should not happen. I'm expecting to get single characters only. 

Those long strings are few in numbers, and I could filter them out. But I'd rather not generate them at all.
So is it me not setting up something properly, or is it a synthtiger bug?
